### ISSUE TITLE
ABI versioning

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm#2967]
Due to https://github.com/conda-forge/staged-recipes/pull/13486, the first OpenMM plugin is going live on conda forge soon. For ABI compatibility, runtime dependencies are expected to be pinned so they use a version compatible with the one used to build the libraries.

As of today, the only version on conda forge is 7.5, so it's not going to be a problem. However, with future releases, if ABI changes, users might end up with a runtime version incompatible with the one a plugin was built with.

The question is: what's the ABI versioning scheme for the OpenMM libraries?

* Major (`x`): All releases within the 7.x series use the same ABI
* Major.minor (`x.x`): All releases within the 7.5 series use the same ABI
* Major.minor.micro (`x.x.x`): There are no ABI guarantees across releases

**Comment by peastman** [comment]
I think we can guarantee ABI compatibility when the third digit changes.  Not when the second digit changes.

**Comment by peastman** [comment]
Though perhaps it would be better to say, "We aspire to maintain compatibility when the third digit changes."  Actually guaranteeing it is difficult.

**Comment by jaimergp** [comment]
Ok, I'll pin with `x.x` then. For future reference, this is how a project linking to OpenMM's libraries should be packaged with conda:

```yaml
requirements:
  build:
    ...
  host:
    - openmm
    ...
  run:
    - {{ pin_compatible('openmm', min_pin='x.x', max_pin='x.x') }}
    ...
```
