### ISSUE TITLE
Further streamline creating a conda-based openmm development environment

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3378]
Further simplifications to the [conda-based development environment install instructions](http://docs.openmm.org/latest/userguide/library/02_compiling.html) should be possible by using either a conda environment file or a conda package.

For example, QCArchive provides a [one-line environment install](http://docs.qcarchive.molssi.org/projects/QCFractal/en/stable/quickstart.html) that simply uses a [conda environment YAML file](https://anaconda.org/QCArchive/qcfractal-snowflake/files) on anaconda cloud that contains the entire specification of the environment.

Alternatively, I wonder if it's possible to even configure and install the appropriate compilers as well.

**Comment by jchodera** [comment]
Here's my start at such a YAML (for `osx`):
```yaml
name: openmm-dev
channels:
  - conda-forge
dependencies:
  - python
  - fftw
  - swig
  - pthread-stubs
  - lxml
  - numpy
  - cython
  - numpy

  #- {{ compiler('c') }}
  #- {{ compiler('cxx') }}
  #- {{ compiler('cuda') }}  # [linux64 or ppc64le or win]
  #- {{ cdt('mesa-libgl-devel') }}  # [linux]

  - cmake
  - make  # [unix]
  #- jom  # [win]
  # needed for Python wrappers
  - doxygen

  # OpenCL ICD
  #- ocl-icd  # [linux]
  #- ocl-icd-system  # [linux]
  #- khronos-opencl-icd-loader  # [win or (osx and opencl_impl == 'khronos')]
  #- ocl_icd_wrapper_apple      # [osx and opencl_impl == 'khronos']

  # Testing
  - git
  - conda-build  # [osx]
  #- m2-findutils  # [win]
  #- m2-coreutils  # [win]
  - pocl      # [linux]
  - pytest
  - pytest-xdist
```
