### ISSUE TITLE
OpenMM 7.7 release candidate roll-out process

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3387]
@peastman : Given the [painful lessons from the OpenMM 7.6 release](https://github.com/openmm/openmm/issues/3232), I wanted to open a thread to discuss the steps we are taking to ensure we don't repeat the same mistakes now that the [OpenMM 7.7 release candidate is out on conda-forge](https://anaconda.org/conda-forge/openmm/files) on the `openmm_rc` channel.

Here's the process I propose to avoid the same mistakes:
- [x] Pushed build to `conda-forge/labels/openmm_rc` label
- [x] [SimTK.org forum announcement](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=14212&p=0&start=0&view=&sid=b5708bafba478edbac1a8c0d5d944873)
- [ ] Cut a [pre-release on GitHub releases, containing detailed release notes](https://github.com/openmm/openmm/releases)
- [ ] Tweet about release candidate
- [ ] Reach out to developer communities harmed by the botched OpenMM 7.6 roll-out to ensure they have opportunity to test 7.7 rc
- [ ] Collect sufficient specific positive feedback (rather than no negative feedback) before moving from release candidate to release
- [ ] Release 7.7

@peastman: The [forum post](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=14212&p=0&start=0&view=&sid=b5708bafba478edbac1a8c0d5d944873) announcing the release candidate just points to [this post about the OpenMM 7.7 beta features](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=14098&p=0&start=0&view=&sid=c4eb10857c219c13eb5724e5592ac019), but doesn't say anything detailed about bugfixes, like [this one that corrupted any free energies computed with OpenMM 7.6](https://github.com/openmm/openmm/issues/3310). We should provide the detailed release notes (including bugfixes) before I tweet more broadly about the release candidate---none of our users want to hunt through the merged commits for that information.

**Comment by jchodera** [comment]
Also, I suggest we remedy [the omission of `scipy`, required for reading some Amber files, before release](https://github.com/conda-forge/openmm-feedstock/issues/66).

**Comment by peastman** [comment]
Feel free to tweet about it or contact other people.  Most of the other things you described are things that would have needed to be done at the beta stage, not release candidate.  That's when we get feedback about API changes.  Once the release candidate is out, the only changes we can make are critical bug fixes.

The release is currently scheduled for tomorrow, and there haven't been any reports of critical bugs that would lead to delaying it.

**Comment by jchodera** [comment]
Um, what?

Are you seriously suggesting that we do absolutely nothing different from
the process that led to the botched OpenMM 7.6 release?

I'm honestly not understanding your rationale here. Can you articulate why
we haven't changed the release process in light of the problems we caused
during the 7.6 release process?

**Comment by jchodera** [comment]
For reference, here is the thread I opened immediately after we started
receiving reports that 7.6 broke a lot of downstream packages that used
OpenMM, and tried to distill lessons and make concrete suggestions about
what we should do differently for the next release:
https://github.com/openmm/openmm/issues/3232

There was plenty of lead time to adjust our practice here.

**Comment by peastman** [comment]
The entire release process for 7.7 has been coordinated in #3191 from the very beginning.  At every point you have known exactly what was happening, what was planned, and what the schedule was.  If you had wanted to suggested changes to the process, doing so on that thread a month ago would have been very helpful.  If you had wanted to tweet about the beta or contact additional people to solicit feedback, that also would have been help.

Waiting until two days before the scheduled release to suddenly suggest a bunch of chances to the process *is not helpful*.  It just creates stress and drama for everyone.  *It is too late to get additional feedback on feature changes.*  That needed to happen during the beta process, as you know perfectly well.  Once the release candidate is out, we cannot make any changes except *critical bug fixes*, and even those only if we're willing to do a new release candidate and delay the release for another week.

**Comment by jchodera** [comment]
> The entire release process for 7.7 has been coordinated in #3191 from the very beginning. At every point you have known exactly what was happening, what was planned, and what the schedule was. If you had wanted to suggested changes to the process, doing so on that thread a month ago would have been very helpful. 

I had opened an entire thread in #3232 to discuss how we should change the release process on Aug 31. This thread was, for the most part, ignored. 

> If you had wanted to tweet about the beta or contact additional people to solicit feedback, that also would have been help.

This isn't my job. Formally, my only job is to help steer the direction of this project and coordinate work. In #3232, I tried to identify how our release process was deficient, and provided concrete suggestions on how we should consider revising it to eliminate the modes of failure we saw with the OpenMM 7.6 release. 
You'll also note I [asked for more information Nov 6 needed for this to be useful](https://github.com/openmm/openmm/issues/3191#issuecomment-962498383), but never received sufficient clarification to actually disseminate useful information about the beta, how to test it, or its main goals.

> Waiting until two days before the scheduled release to suddenly suggest a bunch of chances to the process is not helpful. It just creates stress and drama for everyone. It is too late to get additional feedback on feature changes. That needed to happen during the beta process, as you know perfectly well. Once the release candidate is out, we cannot make any changes except critical bug fixes, and even those only if we're willing to do a new release candidate and delay the release for another week.

It's actually the opposite problem: Nobody knows about the supposed scheduled release date besides you. Nobody has assented to a schedule where today is somehow "two days before the scheduled release". The last update in https://github.com/openmm/openmm/issues/3191 is just an request whether you should start building the release candidate, *which nobody responded in the affirmative to*. 

I think this illustrates how our processes are even more broken than presumed. We need 
1. a better way of tracking release progress in a manner where the process and schedule is visible to everyone
2. a better way of considering changes to the release process

How about this as a solution:
1. Let's proceed as you intend with the release tomorrow **provided we have a quick way to roll back should there be a major issue**
2. We set the two above topics for in-depth discussion in our next leadership meeting

**Comment by jchodera** [comment]
Current 7.7 release checklist is now here: https://github.com/openmm/openmm/issues/3191#issuecomment-1001246492

**Comment by jchodera** [comment]
@peastman : Looks like we're ready to run the FAH benchmarks as well.
What benchmark system(s) and combination(s) of parameters should I set up? The whole benchmark suite might be overkill---what are the high-value benchmarks and parameters for consumer cards?

**Comment by jchodera** [comment]
Here are the benchmarks I already have set up for FAH:

<details>
<summary>FAH Benchmark metadata</summary>

```
RUN0:
    name: DHFR PME
    description: DHFR Joint AMBER-CHARMM benchmark with PME
    num_atoms: 23558
    nonbonded_method: PME
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN1:
    name: DHFR LJPME
    description: DHFR Joint AMBER-CHARMM benchmark with LJPME
    num_atoms: 23558
    nonbonded_method: LJPME
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN2:
    name: DHFR RF
    description: DHFR Joint AMBER-CHARMM benchmark with reaction field electrostatics
    num_atoms: 23558
    nonbonded_method: CutoffPeriodic
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN3:
    name: DHFR PME 4fs BAOAB
    description: DHFR Joint AMBER-CHARMM benchmark with PME with 4 fs timestep
    num_atoms: 23558
    nonbonded_method: PME
    timestep: "4*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN4:
    name: apoa1 PME
    description: ApoA1 benchmark with PME
    num_atoms: 92224
    nonbonded_method: PME
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN5:
    name: apoa1 LJPME
    description: ApoA1 benchmark with LJPME
    num_atoms: 92224
    nonbonded_method: LJPME
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN6:
    name: apoa1 RF
    description: ApoA1 benchmark with reaction field electrostatics
    num_atoms: 92224
    nonbonded_method: CutoffPeriodic
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN7:
    name: apoa1 RF
    description: ApoA1 benchmark with PME with 4 fs BAOAB
    num_atoms: 92224
    nonbonded_method: PME
    timestep: "4*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN8:
    name: COVID Moonshot Sprint testing complex (constrained)
    description: COVID Moonshot Sprint testing perses alchemical free energy calculation ligand in complex
    num_atoms: 89705
    nonbonded_method: PME
    project: 13412
    timestep: "4*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN9:
    name: COVID Moonshot Sprint testing solvent (constrained)
    description: COVID Moonshot Sprint testing perses alchemical free energy calculation ligand in solvent
    num_atoms: 4071
    nonbonded_method: PME
    project: 13413
    timestep: "4*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN10:
    name: SARS-CoV-1 full spike
    description: SARS-CoV-1 full spike
    num_atoms: 371771
    nonbonded_method: PME
    pdbid: 5x58
    project: 14251
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN11:
    name: SARS-CoV-2 full spike
    description: SARS-CoV-2 full spike
    num_atoms: 448584
    nonbonded_method: PME
    pdbid: 6vxx
    project: 14253
    timestep: "2*fs"
    integrator: simtk.openmm.LangevinIntegrator

RUN12:
    name: SARS-CoV-2 Mpro monomer
    description: SARS-CoV-2 main viral protease (Mpro) monomer
    num_atoms: 62180
    nonbonded_method: PME
    pdbid: 6lu7
    project: 11743
    timestep: "4*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN13:
    name: SARS-CoV-2 RBD:ACE2
    description: SARS-CoV-2 RBD:ACE2 (homology model) complex
    num_atoms: 182669
    nonbonded_method: PME
    pdbid: 2afj
    project: 11743
    timestep: "4*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN14:
    name: SARS-CoV-2 RBD:S230 Ab
    description: SARS-CoV-2 RBD (homology model):S230 antibody
    num_atoms: 110730
    nonbonded_method: PME
    pdbid: 6nb8_2ghv
    project: 11745
    timestep: "4*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN15:
    name: COVID Moonshot Sprint 4 complex (unconstrained)
    description: COVID Moonshot Sprint 4 perses alchemical free energy calculation ligand in complex
    num_atoms: 90725
    nonbonded_method: PME
    project: 13424
    timestep: "2*fs"
    integrator: openmmtools.integrators.LangevinIntegrator

RUN16:
    name: COVID Moonshot Sprint 4 solvent (unconstrained)
    description: COVID Moonshot Sprint 4 perses alchemical free energy calculation ligand in solvent
    num_atoms: 4058
    nonbonded_method: PME
    project: 13425
    timestep: "2*fs"
    integrator: openmmtools.integrators.LangevinIntegrator
```
</details>
